graph_config:


custom_model_kwargs:
   # add custom model kwargs here

treename: mmtree/Events;1
selection:
   ### use `&`, `|`, `~` for logical operations on numpy arrays
   ### can use functions from `math`, `np` (numpy), and `awkward` in the expression
   #(jet_tightId==1) & (jet_no<2) & (fj_pt>200) & (fj_pt<2500) & (((sample_isQCD==0) & (fj_isQCD==0)) | ((sample_isQCD==1) & (fj_isQCD==1))) & (event_no%7!=0)
   #(recojet_e>=5)

test_time_selection:
   ### selection to apply at test time (i.e., when running w/ --predict)
   #(jet_tightId==1) & (jet_no<2) & (fj_pt>200) & (fj_pt<2500) & (((sample_isQCD==0) & (fj_isQCD==0)) | ((sample_isQCD==1) & (fj_isQCD==1))) & (event_no%7==0)
   #(recojet_e<5)

new_variables:
   ### [format] name: formula
   ### can use functions from `math`, `np` (numpy), and `awkward` in the expression
   #pfcand_mask: awkward.JaggedArray.ones_like(pfcand_etarel)
   #sv_mask: awkward.JaggedArray.ones_like(sv_etarel)
   #pfcand_mask: awkward.JaggedArray.ones_like(pfcand_e)

preprocess:
  ### method: [manual, auto] - whether to use manually specified parameters for variable standardization
  ### [note]: `[var]_mask` will not be transformed even if `method=auto`

inputs:
  n_jets:
    pad_mode: wrap
    length: 1
    vars:
      - [nFatJet, null]
#      - [nJetId, null]
  jets:
    pad_mode: wrap
    length: 100
    vars:
       - [FatJet_pt, null]
       - [FatJet_eta, null]
       - [FatJet_phi, null]
       - [FatJet_mass, null]
       - [FatJet_area, null]
  n_genjets:
    pad_mode: wrap
    length: 1
    vars:
      - [n_genjet, null]
  genjets:
    pad_mode: wrap
    length: 100
    vars:
       - [GenFatJet_pt, null]
       - [GenFatJet_eta, null]
       - [GenFatJet_phi, null]
       - [GenFatJet_mass, null]
  n_pfcands:
    pad_mode: wrap
    length: 1
    vars:
      - [ nPFCands, null ]
  pfcands:
    pad_mode: wrap
    length: 100
    vars:
       - [PFCands_pt, null]
       - [PFCands_eta, null]
       - [PFCands_phi, null]
       - [PFCands_mass, null]
       - [PFCands_charge, null]
       - [PFCands_pdgId, null]
       - [FatJetPFCands_jetIdx, null]
       - [FatJetPFCands_pFCandsIdx, null]
  n_offline_pfcands:
    pad_mode: wrap
    length: 1
    vars:
      - [ nOfflinePFCands, null ]
  offline_pfcands:
    pad_mode: wrap
    length: 100
    vars:
      - [ OfflinePFCands_pt, null ]
      - [ OfflinePFCands_eta, null ]
      - [ OfflinePFCands_phi, null ]
      - [ OfflinePFCands_mass, null ]
      - [ OfflinePFCands_charge, null ]
      - [ OfflinePFCands_pdgId, null ]
      - [ OfflineFatJetPFCands_jetIdx, null ]
      - [ OfflineFatJetPFCands_pFCandsIdx, null ]
labels:

observers:
   #- recojet_e
   #- recojet_theta
   #- recojet_phi
   #- recojet_m
   #- n_pfcand
