treename: mmtree/Events;1
selection:
   ### use `&`, `|`, `~` for logical operations on numpy arrays
   ### can use functions from `math`, `np` (numpy), and `awkward` in the expression
   #(jet_tightId==1) & (jet_no<2) & (fj_pt>200) & (fj_pt<2500) & (((sample_isQCD==0) & (fj_isQCD==0)) | ((sample_isQCD==1) & (fj_isQCD==1))) & (event_no%7!=0)
   #(recojet_e>=5)

test_time_selection:
   ### selection to apply at test time (i.e., when running w/ --predict)
   #(jet_tightId==1) & (jet_no<2) & (fj_pt>200) & (fj_pt<2500) & (((sample_isQCD==0) & (fj_isQCD==0)) | ((sample_isQCD==1) & (fj_isQCD==1))) & (event_no%7==0)
   #(recojet_e<5)

new_variables:
   ### [format] name: formula
   ### can use functions from `math`, `np` (numpy), and `awkward` in the expression
   #pfcand_mask: awkward.JaggedArray.ones_like(pfcand_etarel)
   #sv_mask: awkward.JaggedArray.ones_like(sv_etarel)
   #pfcand_mask: awkward.JaggedArray.ones_like(pfcand_e)

preprocess:
  ### method: [manual, auto] - whether to use manually specified parameters for variable standardization
  ### [note]: `[var]_mask` will not be transformed even if `method=auto`

inputs:
  n_fat_jets:
    pad_mode: wrap
    length: 1
    vars:
      - [nFatJet, null]
#      - [nJetId, null]
  fat_jets:
    pad_mode: wrap
    length: 50
    vars:
       - [FatJet_pt, null]
       - [FatJet_eta, null]
       - [FatJet_phi, null]
       - [FatJet_mass, null]
  n_jets:
    pad_mode: wrap
    length: 1
    vars:
      - [ nJet, null ]
  jets:
    pad_mode: wrap
    length: 50
    vars:
      - [ Jet_pt, null ]
      - [ Jet_eta, null ]
      - [ Jet_phi, null ]
      - [ Jet_mass, null ]
  n_genjets:
    pad_mode: wrap
    length: 1
    vars:
      - [n_genjet, null]
  genjets:
    pad_mode: wrap
    length: 50
    vars:
       - [GenFatJet_pt, null]
       - [GenFatJet_eta, null]
       - [GenFatJet_phi, null]
       - [GenFatJet_mass, null]
  n_pfcands:
    pad_mode: wrap
    length: 1
    vars:
      - [ nPFCands, null ]
  pfcands:
    pad_mode: wrap
    length: 750
    vars:
       - [PFCands_pt, null]
       - [PFCands_eta, null]
       - [PFCands_phi, null]
       - [PFCands_mass, null]
       - [PFCands_charge, null]
       - [PFCands_pdgId, null]

  pfcands_jet_mapping:
    pad_mode: wrap
    length: 750
    vars:
      - [ FatJetPFCands_jetIdx, null ]
      - [ FatJetPFCands_pFCandsIdx, null ]
  #n_offline_pfcands:
  #  pad_mode: wrap
  #  length: 1
  #  vars:
  #    - [ nOfflinePFCands, null ]
  #offline_pfcands:
  #  pad_mode: wrap
  #  length: 750
  #  vars:
  #    - [ OfflinePFCands_pt, null ]
  #    - [ OfflinePFCands_eta, null ]
  #    - [ OfflinePFCands_phi, null ]
  #    - [ OfflinePFCands_mass, null ]
  #    - [ OfflinePFCands_charge, null ]
  #    - [ OfflinePFCands_pdgId, null ]
  #offline_pfcands_jet_mapping:
  #  pad_mode: wrap
  #  length: 750
  #  vars:
  #    - [ OfflineFatJetPFCands_jetIdx, null ]
  #    - [ OfflineFatJetPFCands_pFCandsIdx, null ]
  MET:
    pad_mode: wrap
    length: 1
    vars:
      - [ MET_pt, null ]
      - [ MET_phi, null ]
      - [ scouting_trig, null]
      - [ offline_trig, null]
      - [ veto_trig, null ]
  n_electrons:
    pad_mode: wrap
    length: 1
    vars:
      - [ nElectron, null ]
  n_photons:
    pad_mode: wrap
    length: 1
    vars:
      - [ nPhotons, null ]
  n_muons:
    pad_mode: wrap
    length: 1
    vars:
      - [ nMuons, null ]
  electrons:
    pad_mode: wrap
    length: 10
    vars:
      - [ Electron_pt, null ]
      - [ Electron_eta, null ]
      - [ Electron_phi, null ]
      - [ Electron_charge, null ]
  muons:
    pad_mode: wrap
    length: 10
    vars:
      - [ Muon_pt, null ]
      - [ Muon_eta, null ]
      - [ Muon_phi, null ]
      - [ Muon_charge, null ]
  photons:
    pad_mode: wrap
    length: 10
    vars:
      - [ Photon_pt, null ]
      - [ Photon_eta, null ]
      - [ Photon_phi, null ]
  matrix_element_gen_particles:
    pad_mode: wrap
    length: 2
    vars:
      - [MatrixElementGenParticle_pt, null]
      - [MatrixElementGenParticle_eta, null]
      - [MatrixElementGenParticle_phi, null]
      - [MatrixElementGenParticle_mass, null]
      - [MatrixElementGenParticle_pdgId, null]
  final_gen_particles:
      pad_mode: wrap
      length: 2000
      vars:
        - [FinalGenParticle_pt, null]
        - [FinalGenParticle_eta, null]
        - [FinalGenParticle_phi, null]
        - [FinalGenParticle_mass, null]
        - [FinalGenParticle_pdgId, null]
        - [FinalGenParticle_status, null]
  final_parton_level_particles:
        pad_mode: wrap
        length: 400
        vars:
            - [FinalPartonLevelParticle_pt, null]
            - [FinalPartonLevelParticle_eta, null]
            - [FinalPartonLevelParticle_phi, null]
            - [FinalPartonLevelParticle_mass, null]
            - [FinalPartonLevelParticle_pdgId, null]
            - [FinalPartonLevelParticle_status, null]

observers:
   #- recojet_e
   #- recojet_theta
   #- recojet_phi
   #- recojet_m
   #- n_pfcand

