treename: Delphes;1
selection:
   ### use `&`, `|`, `~` for logical operations on numpy arrays
   ### can use functions from `math`, `np` (numpy), and `awkward` in the expression
   #(jet_tightId==1) & (jet_no<2) & (fj_pt>200) & (fj_pt<2500) & (((sample_isQCD==0) & (fj_isQCD==0)) | ((sample_isQCD==1) & (fj_isQCD==1))) & (event_no%7!=0)
   #(recojet_e>=5)

test_time_selection:
   ### selection to apply at test time (i.e., when running w/ --predict)
   #(jet_tightId==1) & (jet_no<2) & (fj_pt>200) & (fj_pt<2500) & (((sample_isQCD==0) & (fj_isQCD==0)) | ((sample_isQCD==1) & (fj_isQCD==1))) & (event_no%7==0)
   #(recojet_e<5)

new_variables:
   ### [format] name: formula
   ### can use functions from `math`, `np` (numpy), and `awkward` in the expression
   #pfcand_mask: awkward.JaggedArray.ones_like(pfcand_etarel)
   #sv_mask: awkward.JaggedArray.ones_like(sv_etarel)
   #pfcand_mask: awkward.JaggedArray.ones_like(pfcand_e)

preprocess:
  ### method: [manual, auto] - whether to use manually specified parameters for variable standardization
  ### [note]: `[var]_mask` will not be transformed even if `method=auto`

inputs:
  n_PFCands:
    pad_mode: wrap
    length: 1
    vars:
      - [ ParticleFlowCandidate_size, null ]
  PFCands:
    pad_mode: wrap
    length: 1500
    vars:
       - [ParticleFlowCandidate.Eta, null]
       - [ParticleFlowCandidate.Phi, null]
       - [ParticleFlowCandidate.PT, null]
       - [ParticleFlowCandidate.Mass, null]
       - [ParticleFlowCandidate.Charge, null]
       - [ParticleFlowCandidate.PID, null]
  GenParticles:
      pad_mode: wrap
      length: 7500
      vars:
        - [Particle.Eta, null]
        - [Particle.Phi, null]
        - [Particle.PT, null]
        - [Particle.Charge, null]
        - [Particle.Mass, null]
        - [Particle.PID, null]
        - [Particle.Status, null]
  NParticles:
      pad_mode: wrap
      length: 1
      vars:
          - [Particle_size, null]
observers:
   #- recojet_e
   #- recojet_theta
   #- recojet_phi
   #- recojet_m
   #- n_pfcand


